spring:
  datasource:
    url: jdbc:mysql://localhost:3336/hmos?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root  # 替换为你的MySQL用户名
    password: 123456  # 替换为你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新表结构（首次运行会创建表）
    show-sql: true  # 打印SQL语句（开发环境用）
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# JWT配置
jwt:
  secret: your-secret-key-123456-abcdefghijklmnopqrstuvwxyz0123456789  # 密钥（生产环境需复杂且保密，至少32字符）
  expiration: 86400000  # 令牌过期时间（24小时，单位：毫秒）